### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by javagaorui5944** [zhangtianle/WebSocketChat#4]
天乐哥,期待增加功能一对一,一对多。

**Comment by zhangtianle** [comment]
现在是群聊的，，，好久没做了，以前和我一起写前端的大神现在上班好忙，我一个人也都没搞了

**Comment by javagaorui5944** [comment]
有时间的话给你提交下 code，天乐哥。我前段时间做过 1对1 和 1对多

**Comment by zhangtianle** [comment]
哈哈，好的！我也可以学习学习！
