### ISSUE TITLE
我去。。大佬你怎么不用Maven。。。

### ISSUE THREAD

**Issue by Icemap** [zhangtianle/WebSocketChat#5]
RT。。。

**Comment by zhangtianle** [comment]
ヽ(´•ω•`)､ 啊啊啊，被你发现了，有可能当时还不会，也有可能为了方便。。。。。  我也忘了当时是怎么想的。 有空的时候我改一下吧，或者你也可以帮忙提交一下^_^

**Comment by zhangtianle** [comment]
已添加Maven，  22f8b6b62c12ce6ff9ed154dfe6dcf2fb91b18c4

**Comment by Icemap** [comment]
谢谢大佬。
